
.PHONY: all html clean

HTMLS=index.html coding.html credits.html
PHPS=$(patsubst %.html,%.php,$(HTMLS))

all:
	@echo Usage: make html - makes the HTML output in ./out

html: 


#	php -c . index.php  > $(OUT)/$@
